name: Checkov

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/**

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@de2bfaecd21d58ef232e0d2a3391c33c32c460d7 # v12
        with:
          directory: .
          framework: dockerfile,github_actions
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
          soft_fail: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
        if: always()
        with:
          sarif_file: checkov-results.sarif
