name: Checkov

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/**

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@2fd3901c8feb52417f27f0d9800259a106c1ec1e # v12
        with:
          directory: .
          framework: dockerfile,github_actions
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
          soft_fail: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # v4
        if: always()
        with:
          sarif_file: checkov-results.sarif
