name: Snyk

on:
  push:
    branches: [main]
    paths:
      - pyproject.toml
      - .github/workflows/snyk.yml
  pull_request:
    branches: [main]
    paths:
      - pyproject.toml
      - .github/workflows/snyk.yml
  schedule:
    - cron: "0 6 * * 3"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -e .

      - name: Run Snyk
        id: snyk
        uses: snyk/actions/python@9adf32b1121593767fc3c057af55b55db032dc04 # master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-results.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4
        if: always() && steps.snyk.outcome != 'skipped'
        with:
          sarif_file: snyk-results.sarif
          category: snyk
